#ifndef API_ENGINEDATABASE_H_INCLUDED
#define API_ENGINEDATABASE_H_INCLUDED

enum TypeDB { TYPEDB_SQLITE3 , TYPEDB_MYSQL, TYPEDB_POSTGRES };

enum DatatypesDB { DATATYPES_INTEGER, DATATYPES_REAL, DATATYPES_TEXT, DATATYPES_BLOB};


#endif // API_ENGINEDATABASE_H_INCLUDED
